qtdesigner:
  ui_file: ( windows.mainwindow.kwargs.ui_file )
  qss_file: ( application.kwargs.stylesheet )

vcp:
  name: Mini
  version: v0.0.1
  author: Kurt Jacobson
  description: |
    Mini is minimal example VCP mostly used
    for development and testing purposes.

    Featues:
      * Very tiny
      * Does not do much
      * Not very functioinal
      * Full of bugs
      * Sometimes works

data_plugins:
  status:
    kwargs:
      cycle_time: {{ ini.display.cycle_time }}

dialogs:
  test_dialog:
    provider: qtpy.QtWidgets:QDialog

windows:
  mainwindow:
    provider: mini:MiniVCP
    kwargs:
      ui_file: {{ file.dir }}/mini.ui  # ui file to load the window from
      title: ( vcp.name ) ( vcp.version ) on {{ ini.machine.name }}
      menu:
        - title: File
          items:
          - title: "&Open ..."
            action: file.open
            shortcut: ctrl+o

          - title: "&Recent Files"
            provider: qtpyvcp.widgets.recent_files_menu:RecentFilesMenu

          - title: "&Reload"
            action: file.reload

          - title: "&Close"
            action: file.close

          - title: "Save &As"
            action: file.save_as
            shortcut: esc

          - separator

          - title: Exit
            action: app.exit
            shortcut: ctrl+q

        - title: Machine
          items:
          - title: Home &All
            action: qtpyvcp.actions.machine:home
            args: all



#  secondarywindow:
#    provider: qtpy.QtWidgets:QWidget
#    show: True