qtdesigner:
  ui_file: "{{ windows.mainwindow.kwargs.ui_file }}"
  qss_file: "{{ application.kwargs.stylesheet }}"

vcp:
  name: Mini
  version: v0.0.1
  author: Kurt Jacobson
  description: |
    Mini is minimal example VCP mostly used
    for development and testing purposes.

    Featues:
      * Very tiny
      * Does not do much
      * Not very functioinal
      * Full of bugs
      * Sometimes works

data_plugins:
  status:
    kwargs:
      cycle_time: 75
#  test1:
#    provider: qtpyvcp.plugins:QtPyVCPDataPlugin
#  test2:
#    provider: qtpyvcp.plugins:QtPyVCPDataPlugin
#  test3:
#    provider: qtpyvcp.plugins:QtPyVCPDataPlugin
#  test4:
#    provider: qtpyvcp.plugins:QtPyVCPDataPlugin
#  test5:
#    provider: qtpyvcp.plugins:QtPyVCPDataPlugin

dialogs:
  test_dialog:
    provider: qtpy.QtWidgets:QDialog

windows:
  mainwindow:
    provider: mini:MiniVCP
    kwargs:
#      ui_file: $YAML_DIR$/mini.ui  # ui file to load the window from
      title: "{{ vcp.name }} Example VCP - {{ vcp.version }}"

    menu:
      - title: File
        items:
        - title: "&Open ..."
          action: file.open
          shortcut: ctrl+o

        - title: "&Recent Files"
          provider: qtpyvcp.widgets.recent_files_menu:RecentFilesMenu

        - title: "&Reload"
          action: file.reload

        - title: "&Close"
          action: file.close

        - title: "Save &As"
          action: file.save_as
          shortcut: esc

        - separator

        - title: Exit
          action: app.exit
          shortcut: ctrl+q

      - title: Machine
        items:
        - title: Home &All
          action: qtpyvcp.actions.machine:home
          args: all



#  secondarywindow:
#    provider: qtpy.QtWidgets:QWidget
#    show: True